
#spring:
#    security:
#        oauth2:
#            client:
#                registration:
#                    google:
#                        clientId:  251151229288-qcthm9vcd7tcrkkqqvakg73lika3pgb3.apps.googleusercontent.com
#                        clientSecret: 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
#                        scope:
#                            - email
#                            - profile